### ISSUE TITLE
Exception thrwon into admin > reports > Skill repository

### ISSUE THREAD

**Issue by gabrielrosset** [jfruitet/moodle_referentiel_m27#2]
Hi Jean,
    I just saw another bug concerning some DBMS like SQLServer which does not allow to specify fields in "ORDER BY" clause while they're not in "SELECT" clause.

To reproduce : 
just go to admin menu and click into "reports > Skill repository"

Here is the detail : 

Debug info: SQLState: 42000<br>
Error Code: 145<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Les éléments ORDER BY doivent se retrouver dans la liste de sélection si SELECT DISTINCT est spécifié.<br>

SELECT DISTINCT userid FROM mdl_referentiel_activite WHERE ref_instance='1' ORDER BY userid ASC, date_creation DESC
[array (
0 => '1',
)]
Error code: dmlreadexception
Stack trace:
    line 443 of \lib\dml\moodle_database.php: dml_read_exception thrown
    line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
    line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
    line 850 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
    line 898 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
    line 1084 of \mod\referentiel\locallib.php: call to sqlsrv_native_moodle_database->get_records_sql()
    line 169 of \report\referentiel\index.php: call to referentiel_get_users_activites_instance()

**Comment by gabrielrosset** [comment]
to keep the consistency of the "DISTINCT" clause It seems that the query need a "GROUP BY" clause

**Comment by jfruitet** [comment]
OK.

MySql is much more user friendly than SQL Server or PostGres!

So the correction in locallib.php line 1083

`$sql="SELECT userid, date_creation FROM {referentiel_activite} WHERE ref_instance=:refid  $where $select   GROUP BY userid ORDER BY $order ";
`

**Comment by jfruitet** [comment]
Please try that correction for me because I can't test it myself with my MySql server :>)
If you modify any other SQL clause, please let me know  (there is a lot of such requests in the plugin sources.)

Bonjour,
Pouvez-vous faire la vérification de la correction car je ne dispose pas de SQL Server.
Par ailleurs il risque d'y avoir pas mal de corrections du même type dans tout le reste du programme...
Si vous vous lancez dans les corrections merci de m'envoyer vos scripts modifiés que je les intègre à la version courant du plugin.

Cordialement..
JF.

**Comment by gabrielrosset** [comment]
Yes that's right and event if DML helps to make a code compatible for all DBMS I know it does not remove all stones in developer's shoes. 

Now the problem is that "date_creation" is not in "group by" and not an aggregate too but it seems you do not need it in SELECT right ?

Debug info: SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]La colonne 'mdl_referentiel_activite.date_creation' n'est pas valide dans la liste de sélection parce qu'elle n'est pas contenue dans une fonction d'agrégation ou dans la clause GROUP BY.<br>

SELECT userid, date_creation FROM mdl_referentiel_activite WHERE ref_instance='1' GROUP BY userid ORDER BY userid ASC, date_creation DESC
[array (
0 => '1',
)]
Error code: dmlreadexception

**Comment by jfruitet** [comment]
OK. I'll go deeper in the source code.

**Comment by gabrielrosset** [comment]
I am actually working on other things (mainly MNET & LTI) but if I'm working more deeper into your plugin I'll commit all my changes to this repo for sure

**Comment by jfruitet** [comment]
Thanx.

**Comment by gabrielrosset** [comment]
unfortunately problem is the same selected fields "date_creation" is not into group by so there is the same bug.
In the previous version you didn't have "date_creation" into SELECT are you sure you need it ?

**Comment by gabrielrosset** [comment]
ah well... in "select" or in "order by" is the same, we need an aggregate...
so the solution is a select subquery...

**Comment by jfruitet** [comment]
This function has not to be so sophisticated!
 I have made a radical correction:
Please update the ./mod/referentiel/locallib.php script, line 1084

```
   function referentiel_get_users_activites_instance($referentiel_instance_id){ 
   global $DB;  
   if (!empty($referentiel_instance_id)){

          $params = array("refid" => "$referentiel_instance_id");
          $sql="SELECT DISTINCT userid FROM {referentiel_activite} 
                 WHERE ref_instance=:refid GROUP BY userid ORDER BY userid ";       
          if ($recs = $DB->get_records_sql($sql, $params)){
                 return ($recs);
          }
   }
   return NULL;
   }
```

**Comment by gabrielrosset** [comment]
indeed this solution resolve this issue.
Tkanks for that.
